/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.*;

import java.awt.*;
import java.io.*;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anan Yehia
 */
public class MyFrame extends javax.swing.JFrame {

    public InvoiceController l = new InvoiceController();
    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.setTitle("Sales Invoice Generator");
        Image image = null;
        try {
            File pathToFile = new File("icon.png");
            image = ImageIO.read(pathToFile);
        } catch (IOException ex) {
        }
        this.setIconImage(image);
        createNewInvoice = new javax.swing.JButton();
        deleteInvoice = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InvoiceDate = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InvTab = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        InvDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Add_Line = new javax.swing.JButton();
        Delete_Line = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFile = new javax.swing.JMenuItem();
        saveFile = new javax.swing.JMenuItem();

        Reminder_Label = new javax.swing.JLabel();


        Reminder_Label.setText("#Note: Please press Save Changes button after any editing or adding in any field of the program or the data will not be saved in the files.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                l.formWindowOpened(evt);
            }
        });


        createNewInvoice.setText("Create New Invoice");
        createNewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.createNewInvoiceActionPerformed(evt);
            }
        });

        deleteInvoice.setText("Delete Invoice");
        deleteInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.deleteInvoiceActionPerformed(evt);
            }
        });

        saveBtn.setText("Save Changes");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.cancelBtnActionPerformed(evt);
            }
        });

        Delete_Line.setText("DeleteLine");
        Delete_Line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.Delete_LineBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Invoice Number");

        jLabel3.setText("Invoice Date");

        jLabel4.setText("Customer Name");

        jLabel5.setText("Invoice Total");

        jLabel6.setText("Invoice Items");

        jLabel7.setText("No.");

        InvoiceDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                l.InvoiceDateFocusLost(evt);
            }
        });
        InvoiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.InvoiceDateActionPerformed(evt);
            }
        });

        jLabel8.setText("0.0");
        InvDetails.getColumnModel().getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent evt) {
                l.cellselectionchanged(evt);
            }
        });
        InvTab.setModel(new javax.swing.table.DefaultTableModel(null,
                new String[]{
                        "No.", "Date", "Customer", "Total"
                }
        ));
        InvTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l.InvTabMouseClicked(evt);
            }
        });
        InvTab.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                l.InvTabPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(InvTab);

        InvDetails.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                },
                new String[]{
                        "No.", "Item Name", "Item Price", "Count", "Item Total"
                }
        ));
        InvDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                l.InvDetailsFocusLost(evt);
            }
        });
        InvDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l.InvDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(InvDetails);

        jLabel1.setText("Invoices Table");

        Add_Line.setText("Add Line");
        Add_Line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.Add_LineActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        loadFile.setText("Load");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.loadFileActionPerformed(evt);
            }
        });
        jMenu1.add(loadFile);

        saveFile.setText("Save");
        saveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.saveFileActionPerformed(evt);
            }
        });
        jMenu1.add(saveFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(createNewInvoice)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteInvoice)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(72, 72, 72))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(43, 43, 43)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addComponent(jLabel6)
                                                                                .addGap(0, 429, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel2)
                                                                                        .addComponent(jLabel3)
                                                                                        .addComponent(jLabel4)
                                                                                        .addComponent(jLabel5)
                                                                                )
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(9, 9, 9)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jLabel7)
                                                                                                        .addComponent(InvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jLabel8)
                                                                                                        .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(380, 380, 380)
                                                                .addComponent(Delete_Line)
                                                                .addComponent(Add_Line)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBtn)
                                .addGap(57, 57, 57)
                                .addComponent(cancelBtn)
                                .addGap(120, 120, 120))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(Reminder_Label)
                        )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(InvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel8))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(Add_Line)
                                                        .addComponent(Delete_Line))
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(saveBtn)
                                                        .addComponent(cancelBtn)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(68, 68, 68)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(createNewInvoice)
                                                        .addComponent(deleteInvoice))
                                                .addGap(68, 68, 68)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                                                        .addComponent(Reminder_Label))
                                        ))
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

////    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
////        loadFile();
////    }//GEN-LAST:event_loadFileActionPerformed
//
//    private void saveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileActionPerformed
//        //TODO add your handling code here:
//        saveFile();
//    }//GEN-LAST:event_saveFileActionPerformed
//
//    private void createNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewInvoiceActionPerformed
//        createInvoice();
//
//    }//GEN-LAST:event_createNewInvoiceActionPerformed
//
//    private void deleteInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInvoiceActionPerformed
//        deleteInvoice();
//    }//GEN-LAST:event_deleteInvoiceActionPerformed
//
//    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
//        saveChanges();
//    }//GEN-LAST:event_saveBtnActionPerformed
//
//    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
//        cancelChanges();
//    }//GEN-LAST:event_cancelBtnActionPerformed
//
//    private void InvTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvTabMouseClicked
//        LoadDetails();
//    }//GEN-LAST:event_InvTabMouseClicked
//
//    private void InvTabPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_InvTabPropertyChange
//        // TODO add your handling code here:
//    }//GEN-LAST:event_InvTabPropertyChange

//    private void Add_LineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_LineActionPerformed
//        DefaultTableModel Detailmodel = (DefaultTableModel)InvDetails.getModel();
//        Detailmodel.addRow(new String[]{Detailmodel.getValueAt(0, 0).toString(),"","","",""});
//    }//GEN-LAST:event_Add_LineActionPerformed
//
//    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        InvTab.setDefaultEditor(Object.class, null);
//        loadFile("InvoiceHeader.csv");
//
//    }//GEN-LAST:event_formWindowOpened

//    private void InvDetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InvDetailsFocusLost
////        DefaultTableModel Detailmodel = (DefaultTableModel)InvDetails.getModel();
////        Detailmodel.setValueAt(evt, ERROR, NORMAL);
//    }//GEN-LAST:event_InvDetailsFocusLost
//
//    private void InvDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvDetailsMouseClicked
//        // TODO add your handling code here:
//    }//GEN-LAST:event_InvDetailsMouseClicked
//
//    private void InvoiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceDateActionPerformed
//
//    }//GEN-LAST:event_InvoiceDateActionPerformed
//
//    private void InvoiceDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InvoiceDateFocusLost
//                    String regex = "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[012])-(20[0-9]{2})$";
//                    if(!(InvoiceDate.getText().matches(regex))) {
//                      JOptionPane.showMessageDialog(this,"Wrong Date Format\n Please Enter Date as DD-MM-YYYY ","ERROR",JOptionPane.ERROR_MESSAGE);
//                      InvoiceDate.setText("");
//
//                    }
//    }//GEN-LAST:event_InvoiceDateFocusLost
//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton Add_Line;
    private JButton Delete_Line;
    public JTable InvDetails;
    public JTable InvTab;
    public JTextField InvoiceDate;
    public JButton cancelBtn;
    public JButton createNewInvoice;
    public JTextField customerName;
    public JButton deleteInvoice;
    public JLabel jLabel1;
    public JLabel jLabel2;
    public JLabel jLabel3;
    public JLabel jLabel4;
    public JLabel jLabel5;
    public JLabel jLabel6;
    public JLabel jLabel7;
    public JLabel jLabel8;
    public JLabel Reminder_Label;
    public JMenu jMenu1;
    public JMenuBar jMenuBar1;
    public JScrollPane jScrollPane1;
    public JScrollPane jScrollPane2;
    public JMenuItem loadFile;
    public JButton saveBtn;
    public JMenuItem saveFile;
    // End of variables declaration//GEN-END:variables


}


